// Mocks generated by Mockito 5.4.0 from annotations
// in ejara/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ejara/payment_method/api/payment_method_client.dart' as _i2;
import 'package:ejara/payment_method/models/payment_method.dart' as _i4;
import 'package:ejara/payment_method/models/payment_method_setting.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PaymentMethodClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodClient extends _i1.Mock
    implements _i2.PaymentMethodClient {
  MockPaymentMethodClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PaymentMethod>> fetchAllPaymentMethods() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllPaymentMethods,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.PaymentMethod>>.value(<_i4.PaymentMethod>[]),
      ) as _i3.Future<List<_i4.PaymentMethod>>);
  @override
  _i3.Future<List<_i5.PaymentMethodSetting>> fetchPaymentMethodSettings(
          String? paymentMethodId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPaymentMethodSettings,
          [paymentMethodId],
        ),
        returnValue: _i3.Future<List<_i5.PaymentMethodSetting>>.value(
            <_i5.PaymentMethodSetting>[]),
      ) as _i3.Future<List<_i5.PaymentMethodSetting>>);
}
